export const DEV_DOC_TEMPLATE = `# Dev doc: <title>

> Generated by /dev-review. The template lives in the skill; do not keep a copy in the repository.

## Basics
- **Status**: (awaiting-review / adjusting / approved / in-development / delivered / closed / change-open / bugfix-open)
- **Module**:
- **Target directory**: (code directory to change, e.g. lib/features/finance)
- **Source**: (conversation / module parse / business parse / flow)
- **Raised on**:
- **Delivery date**:

## Background and goal
(Why this is being done, which problem it solves)

## Requirements
(What exactly is wanted, as a list)

## Acceptance criteria
- [ ] (verifiable conditions, one per line)

## Boundaries and non-goals
(What is explicitly out of scope this time)

## Supplementary requirements

## Delivery
### Completed work
| Change | File / location | Notes |
|---|---|---|
|  |  |  |

### Self-test results
(Which commands / tests ran; explain anything that did not run)

### Acceptance steps
1. (How the author verifies by hand)

### Risks and leftovers
- (Known issues, follow-ups)

## Review notes

## Requirement changes

## Defect log
`;

export const MODULE_CARD_TEMPLATE = `# Module: <name>

- **Directory**: lib/features/<name>
- **Docs**: docs/dev-docs/<name>
- **Layers**:
- **Pages**:
- **Responsibilities**:
- **Business breakdown**: not parsed
- **Defect history**: none
- **Business integration**: not integrated
`;
